parameters:
#    fourcoders_latch.example.class: Fourcoders\Bundle\LatchBundle\Example

services:
    fourcoders_latch_listener:
        class: Fourcoders\Bundle\LatchBundle\EventListener\LatchListener
        arguments:
            [@service_container , %latch_app_id% , %latch_app_secret%]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
